name: Fuzz Testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  echidna:
    name: Echidna
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testName:
          - BN256G2EchidnaTest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run Echidna
        uses: crytic/echidna-action@v2
        with:
          solc-version: 0.8.20
          files: .
          contract: ${{ matrix.testName }}
          config: echidna.config.yml
